In [4]:
import numpy as np

In [5]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])

In [8]:
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [10]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
print(a[0])

[1 2 3 4]


In [12]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [13]:
import numpy as np
a = np.array([1, 2, 3])

In [14]:
a

array([1, 2, 3])

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(2)

array([1., 1.])

In [18]:
np.empty(2) 

array([1., 1.])

In [19]:
np.arange(4)

array([0, 1, 2, 3])

In [20]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [21]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [26]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [28]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [30]:
array_example.ndim

3

In [31]:
array_example.size

24

In [32]:
array_example.shape

(3, 2, 4)

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [34]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [35]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [38]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [40]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [42]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [43]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [44]:
data = np.array([1, 2, 3])

data[1]

2

In [45]:
data[0:2]

array([1, 2])

In [46]:
data[1:]

array([2, 3])

In [47]:
data[-2:]

array([2, 3])

In [48]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
print(a[a < 5])

[1 2 3 4]


In [50]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [51]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [52]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [53]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [56]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [57]:
print(a[b])

[1 2 3 4]


In [58]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [59]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [61]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [62]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [63]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [64]:
x = np.arange(1, 25).reshape(2, 12)

In [65]:
x


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [67]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [69]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [70]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [71]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
b2 = a.copy()

In [73]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [75]:
data - ones

array([0, 1])

In [76]:
data * ones

array([1, 2])

In [77]:
data / ones

array([1., 2.])

In [78]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [79]:
b = np.array([[1, 1], [2, 2]])

In [80]:
b.sum(axis=0)

array([3, 3])

In [81]:
b.sum(axis=1)

array([2, 4])

In [82]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [83]:
data.max()

2.0

In [84]:
data.min()

1.0

In [85]:
data.sum()

3.0

In [86]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [87]:
a.sum()

4.8595784

In [88]:
a.min()

0.05093587

In [89]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [90]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
data[0, 1]

2

In [92]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [93]:
data[0:2, 0]

array([1, 3])

In [95]:
data.max()

6

In [96]:
data.min()

1

In [97]:
data.sum()

21

In [98]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [99]:
data.max(axis=0)

array([5, 6])

In [100]:
data.max(axis=1)

array([2, 5, 6])

In [101]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [102]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [103]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [104]:
np.ones(3)

array([1., 1., 1.])

In [105]:
np.zeros(3)

array([0., 0., 0.])

In [106]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.38631479, 0.7808453 , 0.80776855])

In [107]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [108]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [109]:
rng.random((3, 2))

array([[0.67849048, 0.91789814],
       [0.399853  , 0.2996074 ],
       [0.28864945, 0.27783131]])

In [110]:
rng.integers(5, size=(2, 4)) 

array([[1, 1, 2, 3],
       [3, 1, 4, 1]], dtype=int64)

In [111]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [112]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [113]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [114]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [115]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [116]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [117]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [119]:
print(indices)

[0 1 2]


In [120]:
print(occurrence_count)

[2 1 1]


In [121]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [124]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [125]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [126]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
reversed_arr = np.flip(arr)

In [128]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [129]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [130]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [131]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [132]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [133]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [134]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [135]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [136]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [137]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [138]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [139]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
